"""Add total_duration to athlete_progress

Revision ID: 025b7c109eba
Revises: 9b4050a74848
Create Date: 2025-10-19 00:00:10.980114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025b7c109eba'
down_revision = '9b4050a74848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.drop_column('total_duration')

    # ### end Alembic commands ###
