"""empty message

Revision ID: 02fb236fbf29
Revises: ec336d3d4013
Create Date: 2025-09-23 18:33:14.208767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fb236fbf29'
down_revision = 'ec336d3d4013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_suspicious', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('details')
        batch_op.drop_column('is_suspicious')
        batch_op.drop_column('status')

    op.drop_table('support_tickets')
    # ### end Alembic commands ###
