"""empty message

Revision ID: 040fb443e4c7
Revises: fba5517f27c1
Create Date: 2025-10-18 00:49:30.350772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040fb443e4c7'
down_revision = 'fba5517f27c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_goals', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.drop_column('completed_goals')

    # ### end Alembic commands ###
