"""empty message

Revision ID: 05c1d2c30f03
Revises: e9f0ce6d9d25
Create Date: 2025-09-11 06:41:34.248588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c1d2c30f03'
down_revision = 'e9f0ce6d9d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('athlete_plan', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
