"""empty message

Revision ID: 0891093e15fd
Revises: ccd61ceb0175
Create Date: 2025-09-02 03:57:52.625292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0891093e15fd'
down_revision = 'ccd61ceb0175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.drop_column('deadline')
        batch_op.drop_column('current_value')
        batch_op.drop_column('target_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('due_date')
        batch_op.drop_column('tags')
        batch_op.drop_column('status')
        batch_op.drop_column('progress')
        batch_op.drop_column('target')

    # ### end Alembic commands ###
