"""empty message

Revision ID: 0ec6da6cd297
Revises: fc09d69f630d
Create Date: 2025-09-19 00:16:00.184446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec6da6cd297'
down_revision = 'fc09d69f630d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gif_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('muscle_groups', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('equipment_needed', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_calories_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tips', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_index('idx_exercises_category', ['category'], unique=False)
        batch_op.create_index('idx_exercises_difficulty', ['difficulty_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('calories')
        batch_op.drop_column('duration')

    with op.batch_alter_table('workout_log_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pace', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rest_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calories_burned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_heart_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_heart_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_rating', sa.Integer(), nullable=True))
        batch_op.create_index('idx_workout_log_exercises_exercise_id', ['exercise_id'], unique=False)
        batch_op.create_index('idx_workout_log_exercises_log_id', ['workout_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_log_exercises', schema=None) as batch_op:
        batch_op.drop_index('idx_workout_log_exercises_log_id')
        batch_op.drop_index('idx_workout_log_exercises_exercise_id')
        batch_op.drop_column('difficulty_rating')
        batch_op.drop_column('notes')
        batch_op.drop_column('max_heart_rate')
        batch_op.drop_column('avg_heart_rate')
        batch_op.drop_column('calories_burned')
        batch_op.drop_column('rest_time')
        batch_op.drop_column('pace')
        batch_op.drop_column('distance')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calories', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index('idx_exercises_difficulty')
        batch_op.drop_index('idx_exercises_category')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_active')
        batch_op.drop_column('modifications')
        batch_op.drop_column('tips')
        batch_op.drop_column('instructions')
        batch_op.drop_column('default_reps')
        batch_op.drop_column('default_sets')
        batch_op.drop_column('estimated_calories_per_minute')
        batch_op.drop_column('default_duration')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('equipment_needed')
        batch_op.drop_column('muscle_groups')
        batch_op.drop_column('category')
        batch_op.drop_column('gif_url')

    # ### end Alembic commands ###
