"""empty message

Revision ID: 111bd9c06bd7
Revises: 6bda22ccce1c
Create Date: 2025-09-09 17:38:30.551478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111bd9c06bd7'
down_revision = '6bda22ccce1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_coach_athlete', ['coach_id', 'athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_coach_id'), ['coach_id'], unique=False)

    op.create_table('session_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_schedules', schema=None) as batch_op:
        batch_op.create_index('idx_session_schedules_coach_athlete', ['coach_id', 'athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_schedules_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_schedules_coach_id'), ['coach_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_schedules_coach_id'))
        batch_op.drop_index(batch_op.f('ix_session_schedules_athlete_id'))
        batch_op.drop_index('idx_session_schedules_coach_athlete')

    op.drop_table('session_schedules')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_coach_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_athlete_id'))
        batch_op.drop_index('idx_notifications_coach_athlete')

    op.drop_table('notifications')
    # ### end Alembic commands ###
