"""empty message

Revision ID: 1c47fddd8c4b
Revises: 61554a665451
Create Date: 2025-09-11 07:51:46.333812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c47fddd8c4b'
down_revision = '61554a665451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_column('calories_burned')

    # ### end Alembic commands ###
