"""empty message

Revision ID: 1d8c307d821a
Revises: 502452d3125a
Create Date: 2025-08-18 09:23:10.122036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d8c307d821a'
down_revision = '502452d3125a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('injury_risk', sa.String(length=20), nullable=True),
    sa.Column('recovery_prediction', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readiness_scores_date'), ['date'], unique=False)

    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('session_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_workout_logs_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_logs_date'))
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('metrics')
        batch_op.drop_column('duration')
        batch_op.drop_column('session_type')
        batch_op.drop_column('date')

    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readiness_scores_date'))

    op.drop_table('readiness_scores')
    # ### end Alembic commands ###
