"""empty message

Revision ID: 27857437f2e1
Revises: b9d71f5a0d90
Create Date: 2025-09-11 11:37:38.576888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27857437f2e1'
down_revision = 'b9d71f5a0d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_progress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['athlete_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_progress_logs')
    # ### end Alembic commands ###
