"""empty message

Revision ID: 365e16c86d9a
Revises: 1d8c307d821a
Create Date: 2025-08-18 11:23:06.640891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365e16c86d9a'
down_revision = '1d8c307d821a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('athlete_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['athlete_id'], ['id'])

    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('title')
        batch_op.drop_column('athlete_id')

    op.drop_table('feedbacks')
    # ### end Alembic commands ###
