"""empty message

Revision ID: 3a0cfa7d6694
Revises: 63dccc04316a
Create Date: 2025-10-13 08:56:03.822983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0cfa7d6694'
down_revision = '63dccc04316a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_injuries', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('training_intensity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recovery_time', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profiles', schema=None) as batch_op:
        batch_op.drop_column('recovery_time')
        batch_op.drop_column('training_intensity')
        batch_op.drop_column('previous_injuries')

    # ### end Alembic commands ###
