"""empty message

Revision ID: 42d312d69f1d
Revises: 4bcb3dff2733
Create Date: 2025-09-25 23:25:07.860114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d312d69f1d'
down_revision = '4bcb3dff2733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_payment_processed_at', ['processed_at'], unique=False)
        batch_op.create_index('idx_payment_status', ['status'], unique=False)
        batch_op.create_index('idx_payment_subscription_id', ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    with op.batch_alter_table('subscription_usage', schema=None) as batch_op:
        batch_op.create_index('idx_subscription_usage_feature', ['subscription_id', 'feature'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_usage', schema=None) as batch_op:
        batch_op.drop_index('idx_subscription_usage_feature')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index('idx_payment_subscription_id')
        batch_op.drop_index('idx_payment_status')
        batch_op.drop_index('idx_payment_processed_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
