"""empty message

Revision ID: 43a29bfdbf95
Revises: 742956539cc4
Create Date: 2025-09-08 10:54:02.112405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a29bfdbf95'
down_revision = '742956539cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hydration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stress_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('spo2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hrv', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('hrv')
        batch_op.drop_column('spo2')
        batch_op.drop_column('stress_level')
        batch_op.drop_column('mood')
        batch_op.drop_column('hydration')

    # ### end Alembic commands ###
