"""empty message

Revision ID: 483e13a76fd2
Revises: 662d25178b27
Create Date: 2025-09-21 22:03:33.340238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483e13a76fd2'
down_revision = '662d25178b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workout_types', ['workout_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workout_type_id')

    # ### end Alembic commands ###
