"""empty message

Revision ID: 4bcb3dff2733
Revises: 02fb236fbf29
Create Date: 2025-09-25 23:01:24.414217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcb3dff2733'
down_revision = '02fb236fbf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.create_index('idx_login_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_login_logs_ip_status', ['ip_address', 'status'], unique=False)
        batch_op.create_index('idx_login_logs_suspicious', ['is_suspicious'], unique=False)
        batch_op.create_index('idx_login_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_is_suspicious'), ['is_suspicious'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index('idx_support_tickets_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_support_tickets_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index('idx_support_tickets_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_support_tickets_created_at'))
        batch_op.drop_index('idx_support_tickets_user_id')
        batch_op.drop_index('idx_support_tickets_status_priority')
        batch_op.drop_index('idx_support_tickets_created_at')
        batch_op.alter_column('subject',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('admin_response')

    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_logs_status'))
        batch_op.drop_index(batch_op.f('ix_login_logs_is_suspicious'))
        batch_op.drop_index(batch_op.f('ix_login_logs_ip_address'))
        batch_op.drop_index(batch_op.f('ix_login_logs_created_at'))
        batch_op.drop_index('idx_login_logs_user_id')
        batch_op.drop_index('idx_login_logs_suspicious')
        batch_op.drop_index('idx_login_logs_ip_status')
        batch_op.drop_index('idx_login_logs_created_at')
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
