"""empty message

Revision ID: 4d18da6195e1
Revises: 0891093e15fd
Create Date: 2025-09-03 00:55:50.815384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d18da6195e1'
down_revision = '0891093e15fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('current_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'athlete_profiles', ['profile_id'], ['user_id'])
        batch_op.drop_column('progress')
        batch_op.drop_column('status')
        batch_op.drop_column('due_date')
        batch_op.drop_column('target')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('target', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deadline')
        batch_op.drop_column('current_value')
        batch_op.drop_column('target_value')
        batch_op.drop_column('profile_id')

    # ### end Alembic commands ###
