"""empty message

Revision ID: 5da9e28e2770
Revises: 6752f907f05b
Create Date: 2025-09-21 19:50:13.831209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5da9e28e2770'
down_revision = '6752f907f05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercises', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plans', schema=None) as batch_op:
        batch_op.drop_column('exercises')

    # ### end Alembic commands ###
