"""empty message

Revision ID: 6066c4c03acb
Revises: 040fb443e4c7
Create Date: 2025-10-18 00:50:11.188054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6066c4c03acb'
down_revision = '040fb443e4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_goals', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.drop_column('total_goals')

    # ### end Alembic commands ###
