"""empty message

Revision ID: 60d97b5c3c67
Revises: eee1ab45c6d0
Create Date: 2025-09-08 07:25:14.584061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d97b5c3c67'
down_revision = 'eee1ab45c6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_profiles', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
