"""empty message

Revision ID: 61554a665451
Revises: 05c1d2c30f03
Create Date: 2025-09-11 07:48:05.138286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61554a665451'
down_revision = '05c1d2c30f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fats', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calories_burned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steps', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('steps')
        batch_op.drop_column('calories_burned')
        batch_op.drop_column('fats')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')

    # ### end Alembic commands ###
