"""empty message

Revision ID: 63b7ad1607e7
Revises: 8a8a9655e448
Create Date: 2025-09-07 05:01:54.067063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b7ad1607e7'
down_revision = '8a8a9655e448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('calories_intake', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('bp_sys', sa.Integer(), nullable=True),
    sa.Column('bp_dia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.create_index('idx_health_athlete_id', ['athlete_id'], unique=False)
        batch_op.create_index('idx_health_recorded_at', ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_records_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('injury_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('injury_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('imaging_report', sa.String(length=100), nullable=True),
    sa.Column('recovery_strategy', sa.String(length=100), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injury_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injury_records_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_injury_records_reported_at'), ['reported_at'], unique=False)

    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poms_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readiness_scores', schema=None) as batch_op:
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('poms_score')

    with op.batch_alter_table('injury_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injury_records_reported_at'))
        batch_op.drop_index(batch_op.f('ix_injury_records_athlete_id'))

    op.drop_table('injury_records')
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_records_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_health_records_athlete_id'))
        batch_op.drop_index('idx_health_recorded_at')
        batch_op.drop_index('idx_health_athlete_id')

    op.drop_table('health_records')
    # ### end Alembic commands ###
