"""empty message

Revision ID: 63dccc04316a
Revises: dcadff9366ad
Create Date: 2025-10-05 01:54:40.905306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dccc04316a'
down_revision = 'dcadff9366ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
