"""empty message

Revision ID: 6752f907f05b
Revises: a19fc736652a
Create Date: 2025-09-21 19:48:18.128925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6752f907f05b'
down_revision = 'a19fc736652a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('workout_types', schema=None) as batch_op:
        batch_op.create_index('idx_workout_types_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_types', schema=None) as batch_op:
        batch_op.drop_index('idx_workout_types_name')

    op.drop_table('workout_types')
    # ### end Alembic commands ###
