"""empty message

Revision ID: 6ca78f375dd3
Revises: 1c47fddd8c4b
Create Date: 2025-09-11 11:24:52.865175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca78f375dd3'
down_revision = '1c47fddd8c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
