"""empty message

Revision ID: 742956539cc4
Revises: 60d97b5c3c67
Create Date: 2025-09-08 10:37:07.456313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742956539cc4'
down_revision = '60d97b5c3c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.Column('pin_lock', sa.Boolean(), nullable=True),
    sa.Column('apple_health', sa.Boolean(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
