"""empty message

Revision ID: 9a4229434be4
Revises: 111bd9c06bd7
Create Date: 2025-09-09 19:53:14.601269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4229434be4'
down_revision = '111bd9c06bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.create_index('idx_feedback_coach_athlete', ['coach_id', 'athlete_id'], unique=False)
        batch_op.drop_column('text')
    
    op.alter_column('feedbacks', 'text',
        existing_type=sa.Text(),
        nullable=True
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_feedback_coach_athlete')
        batch_op.drop_column('type')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
