"""empty message

Revision ID: 9b4050a74848
Revises: 6066c4c03acb
Create Date: 2025-10-18 00:52:42.134191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4050a74848'
down_revision = '6066c4c03acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_goal_progress', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('health_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.drop_column('health_score')
        batch_op.drop_column('avg_goal_progress')

    # ### end Alembic commands ###
