"""empty message

Revision ID: 9caa5f73b7ee
Revises: 42d312d69f1d
Create Date: 2025-09-28 23:02:23.422409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caa5f73b7ee'
down_revision = '42d312d69f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_goal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bmi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('body_fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('muscle_mass', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fats', sa.Float(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('fats')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('muscle_mass')
        batch_op.drop_column('body_fat')
        batch_op.drop_column('bmi')
        batch_op.drop_column('heart_rate')
        batch_op.drop_column('weight_goal')

    # ### end Alembic commands ###
