"""empty message

Revision ID: b635d8ed3410
Revises: 4d18da6195e1
Create Date: 2025-09-03 01:02:31.882043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b635d8ed3410'
down_revision = '4d18da6195e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.alter_column('target_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.alter_column('target_value',
               existing_type=sa.String(length=150),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
