"""empty message

Revision ID: b9d71f5a0d90
Revises: 6ca78f375dd3
Create Date: 2025-09-11 11:25:18.931131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d71f5a0d90'
down_revision = '6ca78f375dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
