"""Add is_superadmin to User

Revision ID: bdc59cfadae6
Revises: de92c2ffa84a
Create Date: 2025-08-05 21:29:32.934702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc59cfadae6'
down_revision = 'de92c2ffa84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('permissions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('permissions')
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
