"""add athlete goals, schedule, progress tables

Revision ID: ccd61ceb0175
Revises: d3c1c22087e5
Create Date: 2025-09-02 01:03:35.731842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd61ceb0175'
down_revision = 'd3c1c22087e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.create_index('idx_goals_athlete_id', ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_goals_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('athlete_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('workouts_done', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.create_index('idx_progress_athlete_id', ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_progress_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_progress_date'), ['date'], unique=False)

    op.create_table('athlete_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athlete_schedule', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_athlete_id', ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_schedule_athlete_id'), ['athlete_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_schedule_athlete_id'))
        batch_op.drop_index('idx_schedule_athlete_id')

    op.drop_table('athlete_schedule')
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_progress_date'))
        batch_op.drop_index(batch_op.f('ix_athlete_progress_athlete_id'))
        batch_op.drop_index('idx_progress_athlete_id')

    op.drop_table('athlete_progress')
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athlete_goals_athlete_id'))
        batch_op.drop_index('idx_goals_athlete_id')

    op.drop_table('athlete_goals')
    # ### end Alembic commands ###
