"""Add is_superadmin to admin_profile

Revision ID: d71439d009a5
Revises: b91887e598b8
Create Date: 2025-08-13 11:04:08.459751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71439d009a5'
down_revision = 'b91887e598b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
