"""empty message

Revision ID: dcadff9366ad
Revises: 9caa5f73b7ee
Create Date: 2025-09-30 01:15:47.312875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcadff9366ad'
down_revision = '9caa5f73b7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_athlete', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_coach_athlete'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_message_sender_receiver'))
        batch_op.drop_index(batch_op.f('idx_message_sent_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_index(batch_op.f('idx_user_is_deleted'))
        batch_op.drop_index(batch_op.f('idx_user_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('idx_user_id'), ['id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_message_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_message_sender_receiver'), ['sender_id', 'receiver_id'], unique=False)

    with op.batch_alter_table('coach_athlete', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_coach_athlete'), ['coach_id', 'athlete_id', 'is_active'], unique=False)

    # ### end Alembic commands ###
