"""empty message

Revision ID: dee723e8bcc8
Revises: f82e2b0862e9
Create Date: 2025-09-11 11:48:22.185217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee723e8bcc8'
down_revision = 'f82e2b0862e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progress_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_value', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progress_logs', schema=None) as batch_op:
        batch_op.drop_column('recorded_value')

    # ### end Alembic commands ###
