"""empty message

Revision ID: e401897111bc
Revises: 9a4229434be4
Create Date: 2025-09-09 19:59:34.018491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e401897111bc'
down_revision = '9a4229434be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.create_index('idx_feedback_coach_athlete', ['coach_id', 'athlete_id'], unique=False)
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_feedback_coach_athlete')
        batch_op.drop_column('type')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
