"""empty message

Revision ID: e9f0ce6d9d25
Revises: fe05712143a6
Create Date: 2025-09-11 02:55:17.541803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f0ce6d9d25'
down_revision = 'fe05712143a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_goals', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
