"""empty message

Revision ID: ec336d3d4013
Revises: 8d95d9d81f60
Create Date: 2025-09-22 20:56:49.420543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec336d3d4013'
down_revision = '8d95d9d81f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('max_athletes', sa.Integer(), nullable=True),
    sa.Column('max_workouts', sa.Integer(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('priority_support', sa.Boolean(), nullable=True),
    sa.Column('analytics_access', sa.Boolean(), nullable=True),
    sa.Column('custom_branding', sa.Boolean(), nullable=True),
    sa.Column('api_access', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('auto_renew', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('next_billing_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_period_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('usage_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_subscription_end_date', ['end_date'], unique=False)
        batch_op.create_index('idx_subscription_status', ['status'], unique=False)
        batch_op.create_foreign_key(None, 'subscription_plans', ['plan_id'], ['id'])
        batch_op.drop_column('plan_name')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plan_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_subscription_status')
        batch_op.drop_index('idx_subscription_end_date')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('usage_data')
        batch_op.drop_column('cancel_at_period_end')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('canceled_at')
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('current_period_start')
        batch_op.drop_column('next_billing_date')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('auto_renew')
        batch_op.drop_column('trial_end_date')
        batch_op.drop_column('plan_id')

    op.drop_table('subscription_usage')
    op.drop_table('payments')
    op.drop_table('payment_methods')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
