"""Add coach_id to User

Revision ID: ecb167d9674f
Revises: bdc59cfadae6
Create Date: 2025-08-07 21:35:13.147359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb167d9674f'
down_revision = 'bdc59cfadae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_coach', 'user', ['coach_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###
