"""empty message

Revision ID: eee1ab45c6d0
Revises: 63b7ad1607e7
Create Date: 2025-09-08 06:14:48.891207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee1ab45c6d0'
down_revision = '63b7ad1607e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delete_requested_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_users_deleted', ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))
        batch_op.drop_index('idx_users_deleted')
        batch_op.drop_column('delete_requested_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
