"""empty message

Revision ID: f82e2b0862e9
Revises: 27857437f2e1
Create Date: 2025-09-11 11:44:52.238275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82e2b0862e9'
down_revision = '27857437f2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progress_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_progress_logs', schema=None) as batch_op:
        batch_op.drop_column('recorded_at')

    # ### end Alembic commands ###
