"""empty message

Revision ID: fba5517f27c1
Revises: 87300d454452
Create Date: 2025-10-17 20:26:45.488408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fba5517f27c1'
down_revision = '87300d454452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goals_completion_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plan_adherence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('consistency_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_health_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('heart_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('calories_burned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('protein',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('fats',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_progress_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_athlete_progress_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_athlete_progress_date'))
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_athlete_progress_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_athlete_progress_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_progress_athlete_id'), ['athlete_id'], unique=False)
        batch_op.alter_column('fats',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('carbs',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('protein',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('calories_burned',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('heart_rate',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('overall_health_score')
        batch_op.drop_column('consistency_score')
        batch_op.drop_column('plan_adherence')
        batch_op.drop_column('goals_completion_rate')
        batch_op.drop_column('workout_score')

    # ### end Alembic commands ###
