"""empty message

Revision ID: fc09d69f630d
Revises: 95da49ab7c26
Create Date: 2025-09-19 00:07:47.265245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc09d69f630d'
down_revision = '95da49ab7c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('workout_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('planned_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actual_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_heart_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_heart_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hr_zone_anaerobic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hr_zone_aerobic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hr_zone_intensive', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hr_zone_light', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hr_zone_relaxed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_effect_aerobic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_effect_anaerobic', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recovery_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_index(batch_op.f('idx_workout_logs_athlete_id'))
        batch_op.create_index('idx_workout_logs_athlete_date', ['athlete_id', 'date'], unique=False)
        batch_op.create_index('idx_workout_logs_type', ['workout_type'], unique=False)
        batch_op.drop_column('duration')
        batch_op.drop_column('compliance_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compliance_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_workout_logs_type')
        batch_op.drop_index('idx_workout_logs_athlete_date')
        batch_op.create_index(batch_op.f('idx_workout_logs_athlete_id'), ['athlete_id'], unique=False)
        batch_op.drop_column('heart_rate_data')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('notes')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('completion_status')
        batch_op.drop_column('recovery_time')
        batch_op.drop_column('training_effect_anaerobic')
        batch_op.drop_column('training_effect_aerobic')
        batch_op.drop_column('hr_zone_relaxed')
        batch_op.drop_column('hr_zone_light')
        batch_op.drop_column('hr_zone_intensive')
        batch_op.drop_column('hr_zone_aerobic')
        batch_op.drop_column('hr_zone_anaerobic')
        batch_op.drop_column('max_heart_rate')
        batch_op.drop_column('avg_heart_rate')
        batch_op.drop_column('total_time')
        batch_op.drop_column('actual_duration')
        batch_op.drop_column('planned_duration')
        batch_op.drop_column('workout_type')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
