"""empty message

Revision ID: fe05712143a6
Revises: 4fa30ddccd27
Create Date: 2025-09-10 16:20:07.293991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe05712143a6'
down_revision = '4fa30ddccd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_integrations', schema=None) as batch_op:
        batch_op.create_index('idx_health_integrations_athlete', ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_integrations_athlete_id'), ['athlete_id'], unique=False)

    op.create_table('points_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_logs', schema=None) as batch_op:
        batch_op.create_index('idx_points_logs_athlete', ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_logs_athlete_id'), ['athlete_id'], unique=False)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))

    with op.batch_alter_table('points_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_logs_athlete_id'))
        batch_op.drop_index('idx_points_logs_athlete')

    op.drop_table('points_logs')
    with op.batch_alter_table('health_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_integrations_athlete_id'))
        batch_op.drop_index('idx_health_integrations_athlete')

    op.drop_table('health_integrations')
    # ### end Alembic commands ###
